[project]
name = "tldw"
version = "0.1.0"
description = "A console youtube video summarizer"
authors = [{name="Shivansh Sharma", email="shivansh.report@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pytubefix",
    "groq",
    "python-dotenv"
]
